### ISSUE TITLE
PHP install failing on libxml (Ubuntu)

### ISSUE THREAD

**Issue by philipobenito** [skl/phundamental#29]
PHP install is failing at libxml dependency even when it's installed on Ubuntu 12.10

**Comment by skl** [comment]
I take it you were 64bit? Seems to work on a 32bit machine.

**Comment by philipobenito** [comment]
No it was 32bit, I'll try and recreate tomorrow

**Comment by skl** [comment]
My bad I tested on Debian. Will try Ubuntu now and see.

**Comment by skl** [comment]
I've a feeling this is to do with either `/usr/lib` location (see 116695f) or the `libcurl` package (see e09c609). Please test and let me know if this has resolved the issue for you.

Also note that I've deleted `plz` and now using `install` and `uninstall` (see 94c49aa).

**Comment by skl** [comment]
I've a feeling this was just fixed in #32
