### ISSUE TITLE
PHP install failing on LDAPlib Debian 32

### ISSUE THREAD

**Issue by artbar** [skl/phundamental#32]
PHP install is failing. Cannot find LDAP libraries.Debian Wheezy 32 localhost 
![phundamentalinstalphp](https://f.cloud.github.com/assets/3838494/270988/1cd351da-8fd9-11e2-8216-f3306fb36537.png)

**Comment by skl** [comment]
Thanks for the bug report, I'll look into it

**Comment by skl** [comment]
Hi @artbar, see how you get on with that. I've managed to successfully compile PHP 5.4.13 under Wheezy:

```
root@test01:~# uname -a
Linux test01 3.2.0-4-686-pae #1 SMP Debian 3.2.39-2 i686 GNU/Linux
root@test01:~/# php -v
PHP 5.4.13 (cli) (built: Mar 18 2013 19:51:08)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```
