### ISSUE TITLE
XDebug not added to php.ini if already installed

### ISSUE THREAD

**Issue by philipobenito** [skl/phundamental#36]
If you re-compile PHP for any reason (same version) and replace php.ini, if XDebug is already installed, it's not added to php.ini

Also, the sed on zend_extension needs looking at.

**Comment by philipobenito** [comment]
Wasn't just me with sed then? hehe

**Comment by skl** [comment]
Bed time, no regex now :)

**Comment by philipobenito** [comment]
:100: lol
