### ISSUE TITLE
Wrong libmhash version in package_map.conf

### ISSUE THREAD

**Issue by geckolinux** [skl/phundamental#37]
Hi there,

First of all, let me say that Phundamental is absolutely fantastic, just what I was looking for! Thanks so much for developing it.

I ran into a bug trying to install PHP 5.3.26 on Debian Wheezy. It tried to apt-get libmhash3. As far as I can tell this package doesn't exist for Wheezy or any other Debian version. I changed it to libmhash2 in the package_map.conf and it appears to work.

Thanks again!

**Comment by skl** [comment]
Hi @sb56637, thanks for trying phundamental. I've changed the libmhash version in the package map, not sure why it was set to 3 in the first place :)

**Comment by geckolinux** [comment]
Sweet, thanks a lot for the quick fix!
