### ISSUE TITLE
Question: Best practice package upgrades with Phundamental

### ISSUE THREAD

**Issue by geckolinux** [skl/phundamental#38]
Hi everyone, I'm really looking forward to running my VPS with a Phundamental setup. It's exactly what I was looking for. My question is: When a new security release of Nginx or MariaDB comes out, what's the best way to upgrade with Phundamental? Should I try to uninstall first? Or can the script detect that it's an upgrade and overwrite the files?

Thanks a lot!

**Comment by skl** [comment]
Hi @sb56637, each module that phundamental installs is version independent - take a look at the install directories with two versions of PHP installed:

```
/usr/local/php-5.3.26
/etc/php-5.3.26

/usr/local/php-5.4.15
/etc/php-5.4.15
```

The idea is that you install the new version and run it on a different port to test your app first (keeping you live app untouched). If you're happy everything is compatible then you can copy across the configs, uninstall the old version with a `./uninstall php` and bind the new version to the usual port.

The phundamental installer will also never overwrite a file without asking you first - this is to protect your server configuration files such as `php.ini`.

This is a design decision that does make it more difficult than a simple `apt-get upgrade` but allows you the flexibility  to run exactly the version(s) of each module(s) that you require.

I do think there should be a form of simple upgrade process per module but I haven't spent much time in developing a solution for this yet. One use case is that the PEAR/PECL extensions you install will be tied against the version you install them on, so you'll need to install again for a updated version of PHP. I'm open to ideas on how to approach this.

**Comment by skl** [comment]
p.s. If you're not interested in the latest releases from php.net or nginx.org and are happy to stick to what's available in the apt repositories, can I recommend my 5-minute LAMP stack article:
http://skl.me/#the-5-minute-lamp-stack

**Comment by geckolinux** [comment]
Thanks a lot skl for the fast reply!

I'm actually interested in the older versions of PHP needed for Drupal 6, specifically PHP 5.3, which isn't available on Wheezy. So I like the way Phundamental allows me to do this.

So, I tried switching between Nginx mainline and stable releases, and it's pretty smooth. I ran into a few issues, such as insserv complaining about nginx already being installed as a service. But it's all relatively easy to figure out.

I guess I would personally suggest that the module install script try to detect all versions installed and say something like "Module X already has the following versions installed: 1.0, 1.1, 1.3. Pick the version you want to use or type a new version to be installed." If an existing version is typed, it can re-create the necessary symlinks. If a new version is requested, it can do the routine that already exists presently. Then maybe at the end of the script it can say "The following versions are installed: 1.0, 1.1, 1.3, 1.4. Enter the ones you want to remove, if any."

Thanks again for this wonderful script!

**Comment by skl** [comment]
Hi @sb56637, recently I've found myself installing to minor version directories like:

```
/usr/local/php-5.5
/etc/php-5.5

/usr/local/nginx-1.4
/etc/nginx

/usr/local/mariadb-5.5
/etc/my.cnf
```

That way when a new release comes out (e.g. I installed PHP 5.5.6 and PHP 5.5.7 is released) then I just put in the same prefix as before (`/usr/local/php-5.5`) and the installation just overwrites the previous version. In the case of PHP the ABI is not broken until the next minor release (PHP 5.6) so PECL modules do not need to be recompiled or reinstalled and you can keep your old `.pearrc` and `php.ini`. This still allows for multiple PHP version installs (`/usr/local/php-5.3` with `/etc/php-5.3`).

Some time ago I updated all the install scripts to allow for custom prefixes (install directories) in order to work toward this goal.
