### ISSUE TITLE
MariaDB init script doesn't work

### ISSUE THREAD

**Issue by geckolinux** [skl/phundamental#39]
Hi there,

I'm working on configuring a new VPS with the great help of Phundamental. I'm having trouble getting MariaDB to start up after the initial install of Phundamental on a pristine new Debian Wheezy VPS. During setup it asked me the first time configuration questions such as root password and removing the test database. But when I try to run "/etc/init.d/mariadb-5.5.31 start" it fails with "Couldn't find MySQL server (/usr/bin/mysqld_safe) ... failed!". I have verified that /usr/local/bin is first in my path and that mysqld_safe exists there. So I don't know why it's looking in the /usr/bin directory for that file

I'm not sure if this has anything to do with the problem, but at some point during Phundamental setup it apt-get installed the "mysql-common" package, which creates "/etc/mysql/my.cnf". There's also another "my.cnf" file in the /etc main directory. I imagine one of these is the problem that is confusing the startup script.

Any suggestions for a quick fix to get up running, and maybe a fix for Phundamental to make this work out of the box?

Thanks very much! Cheers.

**Comment by skl** [comment]
I've seen this issue before with the init script that comes with the MariaDB source (that's the one that Phundamental uses). From what I remember it involves commenting out the following line in the init script:

```
parse_server_arguments `$print_defaults $extra_args mysqld server mysql_server mysql.server`
```

Although I will test this properly soon.

**Comment by geckolinux** [comment]
Sure enough, that was the problem. Fixed now. Thanks so much!
