### ISSUE TITLE
[Feature request] Non-interactive install

### ISSUE THREAD

**Issue by alexbilbie** [skl/phundamental#42]
Hey,

I use Phundamental to install PHP on our base server images but I have to use it manually because the installer requires manual input.

It'd be great if I could pass command line arguements so that I could fully automate the process and not be asked any questions, e.g:

``` shell
./install php --php-version=5.5.6 --with-xdebug --with-zend-cache --with-apc-u
```

Thanks

**Comment by skl** [comment]
Hi @alexbilbie, this is something I've been thinking about myself too. I'll take a look at it this weekend.

Thanks for the feature request!

**Comment by skl** [comment]
I've gone through all the prompts and started a branch, no implementation yet but thinking along the lines of this:
https://github.com/skl/phundamental/blob/non-interactive/README.md#non-interactive-install-example

**Comment by alexbilbie** [comment]
Looks good to me!

## 

Emailing from my iPhone like a BOSS

**Comment by skl** [comment]
I've made a first attempt at this for the nginx module only, no formal usage yet but arguments are parsed here:
https://github.com/skl/phundamental/blob/382a5629b685151c45126a36d58544c8e3aac4f9/modules/nginx/install.sh#L15

All arguments are optional (same defaults that are displayed on the interactive prompts will be used). Any argument(s) you provide simply act as an override.

Example:

```
# Install with all defaults (latest stable with prefix /usr/local/nginx-1.4)
./phundamental/modules/nginx/install.sh

# Install with custom prefix:
./phundamental/modules/nginx/install.sh --prefix=/opt/nginx
```

Notice that you need to use the nginx installation script directly, not through the `install` front controller script. Standard POSIX exit codes are obeyed so you can detect an installation failure programmatically.

I believe your package manager would still prompt for a `y` to install packages, I will investigate auto-installs for the various package managers (e.g. `apt-get install -y`) but at least this automates some of your workflow.
