### ISSUE TITLE
Unable to install nginx

### ISSUE THREAD

**Issue by mic2100** [skl/phundamental#43]
When using `sudo phundamental/install` I am unable to install nginx. I get the following error `Unknown option install` then the install process exits. I am able to install other packages like PHP, mariadb, etc...

OS: Xubuntu 13.10

If you need any more info let me know

**Comment by skl** [comment]
Thanks @mic2100, this was caused by the new option parsing I put in `modules/nginx/install.sh`. I've added in a case for backwards compatibility.
